Update Metrics.yml

diff --git a/.github/workflows/Metrics.yml b/.github/workflows/Metrics.yml
--- a/.github/workflows/Metrics.yml
+++ b/.github/workflows/Metrics.yml
@@ -14,20 +14,6 @@ jobs:
     permissions:
       contents: write
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Remove old generated SVG files
-        run: |
-          find . -maxdepth 1 -type f -name "*.svg" -delete
-
-      - name: Commit cleanup
-        run: |
-          git config user.name "github-actions[bot]"
-          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
-          git add -A
-          git diff --cached --quiet || git commit -m "Remove old generated SVG files"
-          git push
 
       - name: 📊 Github-metrics
         if: ${{ success() || failure() }}
@@ -133,13 +119,13 @@ jobs:
   #       plugin_music_limit: 5
 
   #   - name: ⏱️ Google PageSpeed
-  #      if: ${{ success() || failure() }}
-  #      uses: martijnlindeman/metrics@master
-  #      with:
-  #        filename: "⏱️ Google PageSpeed.svg"
-  #        token: NOT_NEEDED
-  #        base: ""
-  #        plugin_pagespeed: yes
-  #        plugin_pagespeed_screenshot: yes
-  #        plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
-  #        plugin_pagespeed_url: https://www.martijn-lindeman.com/
+  #     if: ${{ success() || failure() }}
+  #     uses: martijnlindeman/metrics@master
+  #     with:
+  #       filename: "⏱️ Google PageSpeed.svg"
+  #       token: NOT_NEEDED
+  #       base: ""
+  #       plugin_pagespeed: yes
+  #       plugin_pagespeed_screenshot: yes
+  #       plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
+  #       plugin_pagespeed_url: https://www.martijn-lindeman.com/
